/*------------------------------------------------------------------------
                                                                       |
   FILE        : fixed_vects.asm                                       |
   DATE        :  Sat, Feb 14, 2015                                    |
   DESCRIPTION :   define the fixed vector table.                      |
   CPU GROUP   :    29(ROM128K)                                        |
                                                                       |
   This file is generated by KPIT GNU Project Generator (Ver.4.5).     |
                                                                       |
------------------------------------------------------------------------*/
    

/***************************************************************************
 *  Fixed Vector for M16C/60,30,20,10   
 *
 *  Function: define fixed vector table
 *
 **************************************************************************/
 
; Fixed Vector Table

    .section	.vects,"a",@progbits
    .type	_HardwareVectors, @object
    .size	_HardwareVectors, 36
    
_HardwareVectors:
 
    .long    _UndefinedInstruction_ISR
    .long    _Overflow_ISR
    .long    _BRK_Instruction_ISR
    .long    _AddressMatch_ISR
    .long    _SingleStep_ISR
    .long    _WatchdogTimer_ISR
    .long    _DBC_ISR
    .long    _NMI_ISR
    .long    (_start + 0xFF000000) 	;Reset ISR

.end

