/***********************************************************************/
/*                                                                     */
/*  FILE        :hwinit.c                                              */
/*  DATE        :Sat, Feb 14, 2015                                     */
/*  DESCRIPTION :hardware initialization file.                         */
/*  CPU GROUP   :29(ROM128K)                                           */
/*                                                                     */
/*  This file is generated by KPIT GNU Project Generator.              */
/*                                                                     */
/***********************************************************************/

/*********************************************************************
  
 *  hwinit.c : hardware initialization file 
 
 *********************************************************************/
#include "iodefine.h"

void hw_initialise (void)
{
	//hardware initialisation code here
}
