/***********************************************************************/
/*                                                                     */
/*  FILE        :main.c                                                */
/*  DATE        :Sat, Feb 14, 2015                                     */
/*  DESCRIPTION :main program file.                                    */
/*  CPU GROUP   :29(ROM128K)                                           */
/*                                                                     */
/*  This file is generated by KPIT GNU Project Generator.              */
/*                                                                     */
/***********************************************************************/
																							
#include "iodefine.h"
#include "nOS.h"

nOS_Thread threadA;
nOS_Thread threadB;
nOS_Thread threadC;
nOS_Stack stackA[64];
nOS_Stack stackB[64];
nOS_Stack stackC[64];
nOS_Sem semA;
nOS_Sem semB;
nOS_Sem semC;

NOS_ISR(TimerA0_ISR)
{
    nOS_Tick();
}

void ThreadA (void *arg)
{
	while (1) {
        nOS_SemTake(&semA, NOS_WAIT_INFINITE);
	}
}

void ThreadB (void *arg)
{
	while (1) {
        nOS_SemTake(&semB, NOS_WAIT_INFINITE);
        nOS_SemGive(&semA);
	}
}

void ThreadC (void *arg)
{
	while (1) {
        nOS_SemTake(&semC, NOS_WAIT_INFINITE);
        nOS_SemGive(&semB);
	}
}

static void TimerA0_Init(void)
{
    ta0mr.byte = 0x80;
	*(volatile uint16_t *)&ta0 = 0xFFFFU;
	cpsrf.byte = 0x08;
    ta0ic.byte = NOS_CONFIG_MAX_UNSAFE_ISR_PRIO;
    ir_ta0ic = 0;
    
    ta0s = 1;
}

int main (void)
{
    nOS_Init();
    
    nOS_ThreadSetName(NULL, "main");
    
    nOS_SemCreate(&semA, 0, 1);
    nOS_SemCreate(&semB, 0, 1);
    nOS_SemCreate(&semC, 0, 1);

    nOS_ThreadCreate(&threadA, ThreadA, NULL, stackA, 64, NOS_CONFIG_HIGHEST_THREAD_PRIO,   NOS_THREAD_READY, "ThreadA");
    nOS_ThreadCreate(&threadB, ThreadB, NULL, stackB, 64, NOS_CONFIG_HIGHEST_THREAD_PRIO-1, NOS_THREAD_READY, "ThreadB");
    nOS_ThreadCreate(&threadC, ThreadC, NULL, stackC, 64, NOS_CONFIG_HIGHEST_THREAD_PRIO-2, NOS_THREAD_READY, "ThreadC");

    nOS_Start(TimerA0_Init);

    while (1){
        nOS_SemGive(&semC);
    }
}
