/***********************************************************************/
/*                                                                     */
/*  FILE        :var_inthandler.c                                      */
/*  DATE        :Sat, Feb 14, 2015                                     */
/*  DESCRIPTION :varaible vector table definitions.                    */
/*  CPU GROUP   :29(ROM128K)                                           */
/*                                                                     */
/*  This file is generated by KPIT GNU Project Generator.              */
/*                                                                     */
/***********************************************************************/

/***************************************************************************
 *                 define variable vector table for M16C/29
 **************************************************************************/

// BRK				(software int 0)
void	_brk(void) __attribute__ ((interrupt));
void _brk(void){}

// CAN0 wakeup			(software int 1)
void	_can0_wakeup(void) __attribute__ ((interrupt));
void _can0_wakeup(void){}

// CAN0 receive			(software int 2)
void	_can0_receive(void) __attribute__ ((interrupt));
void _can0_receive(void){}

// CAN0 trance			(software int 3)
void	_can0_trance(void) __attribute__ ((interrupt));
void _can0_trance(void){}

// INT3				(software int 4)
void	_int3(void) __attribute__ ((interrupt));
void _int3(void){}

// IC/OC interrupt 0		(software int 5)
void	_ic_oc0(void) __attribute__ ((interrupt));
void _ic_oc0(void){}

// IC/OC interrupt 1,I2Cbus	(software int 6)
void	_ic_oc1(void) __attribute__ ((interrupt));
void _ic_oc1(void){}

// IC/OC Base Timer		(software int 7)
void	_ic_oc_basetimer(void) __attribute__ ((interrupt));
void _ic_oc_basetimer(void){}

// SI/O4,INT5			(software int 8)
void	_int5(void) __attribute__ ((interrupt));
void _int5(void){}

// SI/O3,INT4			(software int 9)
void	_int4(void) __attribute__ ((interrupt));
void _int4(void){}

// UART2 Bus Collision		(software int 10)
void	_uart2_bus_collision(void) __attribute__ ((interrupt));
void _uart2_bus_collision(void){}

// DMA0				(software int 11)
void	_dma0(void) __attribute__ ((interrupt));
void _dma0(void){}

// DMA1				(software int 12)
void	_dma1(void) __attribute__ ((interrupt));
void _dma1(void){}

// CAN0 error			(software int 13)
void	_can0_error(void) __attribute__ ((interrupt));
void _can0_error(void){}

// A-D,input key		(software int 14)
void	_ad_converter(void) __attribute__ ((interrupt));
void _ad_converter(void){}

// uart2 trance/NACK2		(software int 15)
void	_uart2_trance(void) __attribute__ ((interrupt));
void _uart2_trance(void){}

// uart2 receive/ACK2		(software int 16)
void	_uart2_receive(void) __attribute__ ((interrupt));
void _uart2_receive(void){}

#if defined (__STANDARD_IO__) && (defined(__FOUSB__) ||  defined(__E8__))
// uart0 can't be used
#else
// uart0 trance			(software int 17)
void	_uart0_trance(void) __attribute__ ((interrupt));
void _uart0_trance(void){}
#endif

// uart0 receive		(software int 18)
void	_uart0_receive(void) __attribute__ ((interrupt));
void _uart0_receive(void){}

#if defined(__STANDARD_IO__) || defined(__FOUSB__) || defined(__E8__)
// uart1 can't be used
#else
// uart1 trance			(software int 19)
void	_uart1_trance(void) __attribute__ ((interrupt));
void _uart1_trance(void){}
#endif

// uart1 receive		(software int 20)
void	_uart1_receive(void) __attribute__ ((interrupt));
void _uart1_receive(void){}

// TIMER A0			(software int 21)
void	_timer_a0(void) __attribute__ ((interrupt));
void _timer_a0(void){}

// TIMER A1			(software int 22)
void	_timer_a1(void) __attribute__ ((interrupt));
void _timer_a1(void){}

// TIMER A2			(software int 23)
void	_timer_a2(void) __attribute__ ((interrupt));
void _timer_a2(void){}

// TIMER A3			(software int 24)
void	_timer_a3(void) __attribute__ ((interrupt));
void _timer_a3(void){}

// TIMER A4			(software int 25)
void	_timer_a4(void) __attribute__ ((interrupt));
void _timer_a4(void){}

// timer b0			(software int 26)
void	_timer_b0(void) __attribute__ ((interrupt));
void _timer_b0(void){}

// timer b1			(software int 27)
void	_timer_b1(void) __attribute__ ((interrupt));
void _timer_b1(void){}

// timer b2			(software int 28)
void	_timer_b2(void) __attribute__ ((interrupt));
void _timer_b2(void){}

// int0				(software int 29)
void	_int0(void) __attribute__ ((interrupt));
void _int0(void){}

// int1				(software int 30)
void	_int1(void) __attribute__ ((interrupt));
void _int1(void){}

// int2				(software int 31)
void	_int2(void) __attribute__ ((interrupt));
void _int2(void){}

// software int 32 for user or MR30
// software int 33 for user or MR30
// software int 34 for user or MR30
// software int 35 for user or MR30
// software int 36 for user or MR30
// software int 37 for user or MR30
// software int 38 for user or MR30
// software int 39 for user or MR30
// software int 40 for user or MR30
// software int 41 for user or MR30
// software int 42 for user or MR30
// software int 43 for user or MR30
// software int 44 for user or MR30
// software int 45 for user or MR30
// software int 46 for user or MR30
// software int 47 for user or MR30
// software int 48 for user
// software int 49 for user
// software int 50 for user
// software int 51 for user
// software int 52 for user
// software int 53 for user
// software int 54 for user
// software int 55 for user
// software int 56 for user
// software int 57 for user
// software int 58 for user
// software int 59 for user
// software int 60 for user
// software int 61 for user
// software int 62 for user
// software int 63 for user

